### ISSUE TITLE
Support for PNG

### ISSUE THREAD

**Issue by London-Lass** [Ankit404butfound/PyWhatKit#157]
## Related Problem

WhatsApp appears to support sending a PNG image, however  PyWhatKit doesn't.

## Feature Description

Would it be possible to add support for PNG images?

**Comment by Naman23-coder** [comment]
We'll check it soon

**Comment by rvaquerizor** [comment]
@London-Lass 
I am currently able to send PNG images using PyWhatKit v5.2.

A different issue is that sending files seems to be very sensitive to your _wait_time_ and _close_time_ values.
And not only that, for the same values used, sometimes it succeeds and others it fails.

**Comment by aaryanrr** [comment]
Yes, the library supports sending PNG on Windows and Linux distributions, please update your installation @London-Lass. 
@rvaquerizor this is because we are automating the GUI to send a message. WhatsApp Web takes different amount of time to load depending upon your network speed and various other factors.
